### ISSUE TITLE
Latest google-gax appears to break.

### ISSUE THREAD

**Issue by daspecster** [googleapis/googleapis#245]
Here's a trace from `google-cloud-python` importing `error_reporting`

```bash
>>> from google.cloud import error_reporting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/cloud/error_reporting/__init__.py", line 18, in <module>
    from google.cloud.error_reporting.client import Client
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/cloud/error_reporting/client.py", line 19, in <module>
    import google.cloud.logging.client
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/cloud/logging/__init__.py", line 18, in <module>
    from google.cloud.logging.client import Client
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/cloud/logging/client.py", line 21, in <module>
    from google.cloud.logging._gax import make_gax_logging_api
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/cloud/logging/_gax.py", line 19, in <module>
    from google.cloud.gapic.logging.v2.config_service_v2_client import (
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/cloud/gapic/logging/v2/config_service_v2_client.py", line 30, in <module>
    from google.gax import api_callable
  File "/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/google/gax/__init__.py", line 49, in <module>
    with open('%s%sVERSION' % (CUR_DIR, os.path.sep), 'r') as version_file:
IOError: [Errno 2] No such file or directory: '/.virtualenvs/test-broken-gcp/lib/python2.7/site-packages/VERSION'
```

Failing build: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/196213478#L245

**Comment by lukesneeringer** [comment]
Making the actual fix in a new PR shortly (we rolled back for now).
