### ISSUE TITLE
LoadError with google-apis-protos-types

### ISSUE THREAD

**Issue by StuartHadfield** [googleapis/googleapis#469]
Hi,

I'm trying to use some Google APIs in a rails app which I am deploying via k8s.  I had a similar issue with google-gax 0.8.9 which was subsequently fixed in 0.8.10.  It seems like there's a file permissions issues not unlike the one outlined [here](https://github.com/googleapis/gax-ruby/issues/54).
For now I've elected to add `RUN find $(bundle show googleapis-common-protos) -type f -perm 640 -print -exec chmod 644 {} \;` which I am testing right now - but it would be lovely if there was a concrete resolution to this issue.

Stack trace:
```
15:23:51 Found 2 pods, using pod/zappi-io-database-migrate-27005-6t525
15:23:51 rake aborted!
15:23:51 LoadError: cannot load such file -- /srv/bundle/gems/googleapis-common-protos-types-1.0.0/lib/google/api/annotations_pb.rb
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/v1/image_annotator_pb.rb:6:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/v1/image_annotator_client.rb:29:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/v1.rb:15:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/service.rb:18:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/project.rb:18:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision.rb:17:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:23:51 /srv/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:23:51 /srv/bundle/bundler/gems/my-app-4b4c76abd6e3/lib/my_app.rb:20:in `<top (required)>'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
15:23:51 /srv/code/config/application.rb:7:in `<top (required)>'
15:23:51 /srv/code/Rakefile:5:in `require'
15:23:51 /srv/code/Rakefile:5:in `<top (required)>'
15:23:51 /usr/local/rbenv/versions/2.3.3/bin/bundle:23:in `load'
15:23:51 /usr/local/rbenv/versions/2.3.3/bin/bundle:23:in `<main>'
15:23:51 (See full trace by running task with --trace)
```

Ruby Version 2.3.3p222 (2016-11-21 revision 56859)

**Comment by StuartHadfield** [comment]
`RUN find $(bundle show googleapis-common-protos) -type f -perm 640 -print -exec chmod 644 {} \;`

Did not solve my problem.  Will continue looking for a workaround today.

**Comment by StuartHadfield** [comment]
I overlooked something:
To get deploys working I had to add:
```
RUN find $(bundle show googleapis-common-protos) -type f -perm 640 -print -exec chmod 644 {} \; && \
    find $(bundle show googleapis-common-protos-types) -type f -perm 640 -print -exec chmod 644 {} \;
```

There are permissions issues with both `common-protos` and `common-protos-types` and the find was only resolving `common-protos`

**Comment by alanctgardner** [comment]
Just to add a voice to this: both `googleapis-common-protos` and `googleapis-common-protos-types` install files that aren't world-readable. This is pretty inconvenient for all the reasons listed in the linked ticket - if your deploy user isn't also running the service it can't load this gem and the error is super obscure.
